### ISSUE TITLE
How to broadcast raw tx?

### ISSUE THREAD

**Issue by guotie** [vacuumlabs/cardanolite#179]
I don't found any API in cardano node

**Comment by refi93** [comment]
Here is the code of the endpoint we created to submit txs to cardano network: https://github.com/vacuumlabs/cardanolite/blob/master/server/transactionSubmitter.js

We had to make it a server endpoint, since the tx submission is made in raw TCP to the cardano nodes. We basically reverse engineered it with wireshark from Daedalus, so bear in mind that this is not official and it may stop working at any time, although it seems to have worked fine for the last 5-6 months.

**Comment by refi93** [comment]
You may also be interested in taking a look at Project Icarus - a reference wallet implementation by IOHK (relatively new, under development) where tx submission should also be handled: https://github.com/input-output-hk/project-icarus Sooner or later, we will probably adhere to this official implementation, which was not available at the time of making ours.
