### ISSUE TITLE
Derivation of addresses from xpub

### ISSUE THREAD

**Issue by rahilzebpay** [vacuumlabs/cardanolite#72]
Is there any method exposed that allows address derivation from Xpub?

**Comment by refi93** [comment]
@rahilzebpay No, there isn't. We have ported only the whole keypair and address derivation, but you can port it in an, I believe, quite straightforward way from the official cardano repository if you would like to, just take a look there: https://github.com/input-output-hk/cardano-crypto/blob/0da8bd64ec81dc7621fe709aff23e3c08ae56a23/cbits/encrypted_sign.c at the function wallet_encrypted_derive_public. Then you would need to use the parent HdNode (without the private key, ofcourse, or with a "fake" private key of zeros) and the derived (partial - withou secret key again) Hd Node to encode the address similarly as we do in the deriveAddressWithHdNode function.

You can take inspiration from our port of the wallet_encrypted_derive_private function to our deriveHdNodeIteration function there: https://github.com/vacuumlabs/cardano/blob/master/wallet/address.js. It should be pretty much the same and the majority of the functions involved in the computation if not all should be ported already.

**Comment by refi93** [comment]
@rahilzebpay We have recently added xpub derivation in our "develop" branch, by linking a fork of the js-cardano-wasm library: https://github.com/vacuumlabs/js-cardanolite-wasm Here is the snippet of code froum our codebase showing how to use it: https://github.com/vacuumlabs/cardanolite/blob/develop/wallet/helpers/derivePublic.js

We had to make this fork because the original js-cardano-wasm references an old commit from the rust repo (https://github.com/input-output-hk/rust-cardano/tree/master) where is a bug in the V1 derivation of keys which is the one we and Daedalus uses and the original js-cardano-wasm uses V2 derivation - new version of the derivation scheme of keys with slight changes.

**Comment by refi93** [comment]
solved in https://github.com/vacuumlabs/cardanolite/pull/81
